const CHECK_USER_SESSION = "CHECK_USER_SESSION";
const EMAIL_SIGN_IN_START = "EMAIL_SIGN_IN_START";
const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START";
const SET_USER = "SET_USER";
const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";
const SIGN_OUT_START = "SIGN_OUT_START";
const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
const SIGN_UP_START = "SIGN_UP_START";
const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";

export {
  CHECK_USER_SESSION,
  EMAIL_SIGN_IN_START,
  GOOGLE_SIGN_IN_START,
  SET_USER,
  SIGN_IN_FAILURE,
  SIGN_IN_SUCCESS,
  SIGN_OUT_FAILURE,
  SIGN_OUT_START,
  SIGN_OUT_SUCCESS,
  SIGN_UP_FAILURE,
  SIGN_UP_START,
  SIGN_UP_SUCCESS
};
