export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const TOGGLE_CART_SHOWN = "TOGGLE_CART_SHOWN";
