const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
const CLEAR_CART = "CLEAR_CART";
const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
const REMOVE_ITEM = "REMOVE_ITEM";
const TOGGLE_CART_SHOWN = "TOGGLE_CART_SHOWN";

export {
  ADD_ITEM_TO_CART,
  CLEAR_CART,
  CLEAR_ITEM_FROM_CART,
  REMOVE_ITEM,
  TOGGLE_CART_SHOWN
};
